version: 2
jobs:
  server:
    working_directory: ~/server
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: organizer3000-server-{{ checksum "server/pom.xml" }}
      - run: cd server && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/server/.m2
          key: organizer3000-server-{{ checksum "server/pom.xml" }}
      - run: cd server && mvn package
      - store_test_results:
          path: server/target/surefire-reports
      - store_artifacts:
          path: server/target/organizer3000-server-0.0.1-SNAPSHOT.jar

  client:
    working_directory: ~/client
    docker:
      - image: circleci/node:10.15-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'cd client && sudo npm install -g npm@latest'
      - restore_cache:
          key: organizer3000-client-{{ checksum "client/package.json" }}
      - run:
          name: install-npm-wee
          command: cd client && npm install
      - save_cache:
          key: organizer3000-client-{{ checksum "client/package.json" }}
          paths:
            - ./client/node_modules
      - run:
          name: test
          command: cd client && npm run test:single
      # - run:
      #     name: code-coverage
      #     command: './client/node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: client/test-results.xml
          prefix: tests
      # - store_artifacts:
      #     path: client/coverage
      #     prefix: coverage
      - store_test_results:
          path: client/test-results.xml
workflows:
  version: 2
  build_and_test:
    jobs:
      - server
      - client