version: "3"
services:
  mysql:
    container_name: app-mysql
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/install_db.sql"

  server:
    restart: always
    build: ./server
    working_dir: /server
    volumes:
      - ./server:/server
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql

  client:
    build: ./client
    working_dir: /client
    ports:
      - "4200:4200" # doesn't work, or works but dev server sends nothing.
      - "49153:49153" # Webpack hot reload
    volumes:
      - ./client:/client
    command: npm run start
